#ifndef ZERO_C_X64_EMIT_H
#define ZERO_C_X64_EMIT_H

#include "zero.h"

#include <stdint.h>

void z_x64_append_u8(ZBuf *buf, unsigned value);
void z_x64_append_u32(ZBuf *buf, uint32_t value);
void z_x64_append_u64(ZBuf *buf, uint64_t value);
void z_x64_patch_u32(ZBuf *buf, size_t offset, uint32_t value);
void z_x64_patch_rel32(ZBuf *buf, size_t patch_offset, size_t target_offset);
size_t z_x64_emit_jmp32_placeholder(ZBuf *buf, unsigned opcode);
size_t z_x64_emit_call32_placeholder(ZBuf *buf);
size_t z_x64_emit_call_rip32_placeholder(ZBuf *buf);
size_t z_x64_emit_jcc32_placeholder(ZBuf *buf, unsigned condition);
void z_x64_emit_rbp_disp_reg(ZBuf *buf, unsigned opcode, unsigned reg, unsigned offset, bool wide);
void z_x64_emit_load_rbp_positive_reg(ZBuf *buf, unsigned reg, unsigned offset, bool wide);
void z_x64_emit_load_rsp_offset_reg(ZBuf *buf, unsigned reg, unsigned offset, bool wide);
void z_x64_emit_store_rsp_offset_reg(ZBuf *buf, unsigned reg, unsigned offset, bool wide);
void z_x64_emit_lea_rsp_offset_reg(ZBuf *buf, unsigned reg, unsigned offset);
void z_x64_emit_mov_rsp_offset_u32(ZBuf *buf, unsigned offset, uint32_t value, bool wide);
void z_x64_emit_inc_rsp_offset64(ZBuf *buf, unsigned offset);
void z_x64_emit_add_rax_rsp_offset(ZBuf *buf, unsigned offset);
void z_x64_emit_cmp_rax_rsp_offset(ZBuf *buf, unsigned offset);
void z_x64_emit_cmp_reg_reg(ZBuf *buf, unsigned lhs, unsigned rhs, bool wide);
void z_x64_emit_cmp_reg_i8(ZBuf *buf, unsigned reg, int8_t value, bool wide);
void z_x64_emit_mov_reg_from_rax(ZBuf *buf, unsigned reg, bool wide);
void z_x64_emit_mov_reg_from_reg(ZBuf *buf, unsigned dst_reg, unsigned src_reg, bool wide);
void z_x64_emit_mov_reg_u32(ZBuf *buf, unsigned reg, uint32_t value);
void z_x64_emit_mov_reg_i32(ZBuf *buf, unsigned reg, int32_t value);
void z_x64_emit_mov_reg_u64(ZBuf *buf, unsigned reg, uint64_t value);
void z_x64_emit_xor_reg_reg(ZBuf *buf, unsigned reg, bool wide);
void z_x64_emit_add_reg_reg(ZBuf *buf, unsigned dst_reg, unsigned src_reg, bool wide);
void z_x64_emit_sub_reg_reg(ZBuf *buf, unsigned dst_reg, unsigned src_reg, bool wide);
void z_x64_emit_xor_reg_from_reg(ZBuf *buf, unsigned dst_reg, unsigned src_reg, bool wide);
void z_x64_emit_add_reg_i8(ZBuf *buf, unsigned reg, int8_t value, bool wide);
void z_x64_emit_and_reg_i8(ZBuf *buf, unsigned reg, int8_t value, bool wide);
void z_x64_emit_and_reg_u32(ZBuf *buf, unsigned reg, uint32_t value, bool wide);
void z_x64_emit_neg_reg(ZBuf *buf, unsigned reg, bool wide);
void z_x64_emit_shr_reg_one(ZBuf *buf, unsigned reg, bool wide);
void z_x64_emit_shl_reg_imm8(ZBuf *buf, unsigned reg, unsigned amount, bool wide);
void z_x64_emit_shr_reg_imm8(ZBuf *buf, unsigned reg, unsigned amount, bool wide);
void z_x64_emit_imul_reg_i32(ZBuf *buf, unsigned reg, int32_t value, bool wide);
void z_x64_emit_add_rax_u32(ZBuf *buf, uint32_t value, bool wide);
void z_x64_emit_sub_rax_u32(ZBuf *buf, uint32_t value, bool wide);
void z_x64_emit_load_reg8_base_index(ZBuf *buf, unsigned dst_reg, unsigned base_reg, unsigned index_reg);
void z_x64_emit_movzx_reg32_base_index_u8(ZBuf *buf, unsigned dst_reg, unsigned base_reg, unsigned index_reg);
void z_x64_emit_store_base_index_reg8(ZBuf *buf, unsigned base_reg, unsigned index_reg, unsigned src_reg);
void z_x64_emit_cmp_base_index_reg8(ZBuf *buf, unsigned base_reg, unsigned index_reg, unsigned reg);
void z_x64_emit_cmp_base_index_u8(ZBuf *buf, unsigned base_reg, unsigned index_reg, unsigned value);
void z_x64_emit_lea_base_index_disp_reg(ZBuf *buf, unsigned dst_reg, unsigned base_reg, unsigned index_reg, unsigned disp);
void z_x64_emit_xor_r8d_r8d(ZBuf *buf);
void z_x64_emit_push_reg64(ZBuf *buf, unsigned reg);
void z_x64_emit_pop_reg64(ZBuf *buf, unsigned reg);
void z_x64_emit_push_rax(ZBuf *buf);
void z_x64_emit_pop_rax(ZBuf *buf);
void z_x64_emit_mov_rcx_from_rax(ZBuf *buf, bool wide);
void z_x64_emit_mov_r9_from_rax(ZBuf *buf);
void z_x64_emit_mov_rax_from_rcx(ZBuf *buf);
void z_x64_emit_mov_rdx_from_rax(ZBuf *buf);
void z_x64_emit_mov_rdi_from_rax(ZBuf *buf);
void z_x64_emit_mov_rsi_from_rax(ZBuf *buf);
void z_x64_emit_mov_rsi_from_rsp(ZBuf *buf);
void z_x64_emit_mov_rax_from_rdx(ZBuf *buf);
void z_x64_emit_mov_rax_from_rdi(ZBuf *buf);
void z_x64_emit_mov_eax_from_ecx(ZBuf *buf);
size_t z_x64_emit_mov_rax_u64_patchable(ZBuf *buf, uint64_t value);
void z_x64_emit_mov_rax_u64(ZBuf *buf, uint64_t value);
void z_x64_emit_xor_eax_eax(ZBuf *buf);
void z_x64_emit_xor_ecx_ecx(ZBuf *buf);
void z_x64_emit_xor_rdi_rdi(ZBuf *buf);
void z_x64_emit_xor_rax_rax(ZBuf *buf);
void z_x64_emit_inc_ecx(ZBuf *buf);
void z_x64_emit_inc_rcx(ZBuf *buf);
void z_x64_emit_inc_r8(ZBuf *buf);
void z_x64_emit_dec_r8d(ZBuf *buf);
void z_x64_emit_add_rax_rcx(ZBuf *buf, bool wide);
void z_x64_emit_sub_rax_rcx(ZBuf *buf, bool wide);
void z_x64_emit_imul_rax_rcx(ZBuf *buf, bool wide);
void z_x64_emit_and_rax_rcx(ZBuf *buf, bool wide);
void z_x64_emit_or_rax_rcx(ZBuf *buf, bool wide);
void z_x64_emit_add_rdx_rcx(ZBuf *buf, bool wide);
void z_x64_emit_shl_rcx_imm8(ZBuf *buf, unsigned amount);
void z_x64_emit_shr_rcx_imm8(ZBuf *buf, unsigned amount);
void z_x64_emit_load_eax_ptr_rax_u8(ZBuf *buf);
void z_x64_emit_load_eax_ptr_rax(ZBuf *buf);
void z_x64_emit_load_rax_ptr_rax(ZBuf *buf);
void z_x64_emit_load_eax_ptr_rdx_u8(ZBuf *buf);
void z_x64_emit_load_eax_ptr_rdx(ZBuf *buf);
void z_x64_emit_store_ptr_rdx_al(ZBuf *buf);
void z_x64_emit_store_ptr_rdx_eax(ZBuf *buf);
void z_x64_emit_div_rax_rcx(ZBuf *buf, bool wide, bool uns, bool keep_remainder);
void z_x64_emit_test_reg_reg(ZBuf *buf, unsigned reg, bool wide);
void z_x64_emit_test_rax_rax(ZBuf *buf, bool wide);
void z_x64_emit_test_ecx_ecx(ZBuf *buf);
void z_x64_emit_cmp_rax_rcx(ZBuf *buf, bool wide);
void z_x64_emit_setcc_al_to_bool(ZBuf *buf, unsigned setcc_opcode);
void z_x64_emit_cmp_rax_rcx_to_bool(ZBuf *buf, unsigned setcc_opcode, bool wide);
void z_x64_emit_bool_from_nonnegative_rax(ZBuf *buf);
void z_x64_emit_prologue(ZBuf *buf, unsigned stack_size);
void z_x64_emit_epilogue(ZBuf *buf);
void z_x64_emit_mov_eax_u32(ZBuf *buf, uint32_t value);
void z_x64_emit_ud2(ZBuf *buf);
void z_x64_emit_syscall(ZBuf *buf);
void z_x64_emit_sub_rsp(ZBuf *buf, unsigned amount);
void z_x64_emit_add_rsp(ZBuf *buf, unsigned amount);

#endif
